### PR TITLE
Feature/dockerize

### PR DESCRIPTION
**Pull request by EchedeyLR**

### CODE REVIEW

**Comment by daoudclarke** [comment]
Great stuff!

I'm not convinced we need the `entrypoint.sh` - can we not just call `main.py` directly?

**Comment by EchedeyLR** [comment]
The idea of the entrypoint is allowing configurable number of threads by environment variable.

If you know another way of doing that in the Dockerfile without having to rebuild it or similar (as we would not have the `entrypoint.sh`, I am open to suggestions.

**Comment by EchedeyLR** [comment]
Also, in the future, several embedded Python variables listed should be configurable too by environment variables so the software can be reused without rebuilding the whole image.

**Comment by daoudclarke** [comment]
ah got it - let's leave it as is for now, and at a later point we'll read the env var in the python script itself.

**Pull request merged**
